### ISSUE TITLE
Node Package?

### ISSUE THREAD

**Issue by zbeekman** [cookiengineer/git-ddiff#1]
What's the recommended installation procedure? Just throw git-ddiff.js on your path, `chmod +x` it and off you go? Since it requires node anyway, it would be convenient to be able to install it with npm... just a  thought.

Cheers!

**Comment by cookiengineer** [comment]
Good idea, gonna create an npm package for it when I'm back at my computer!

**Comment by Scooby613** [comment]
Geting all kinds of error codes diffrent apps being added and the cech on apps read 0 but are stiil on

**Comment by cookiengineer** [comment]
> Geting all kinds of error codes diffrent apps being added and the cech on apps read 0 but are stiil on

I think you are in the wrong repo.

**Comment by cookiengineer** [comment]
@zbeekman The NPM package is now ready.

```bash
sudo npm install -g git-ddiff;
```
