### ISSUE TITLE
Git already does this

### ISSUE THREAD

**Issue by adamchainz** [cookiengineer/git-ddiff#2]
Try running `git diff 'master@{3 days ago}'` or pretty much any other date expression in the brackets. Docs: "reflog shortnames" at https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection

**Comment by cookiengineer** [comment]
For reference: https://www.reddit.com/r/programming/comments/69j3ir/gitddiff_a_better_git_diff_for_humans_with_lack/dh78l46/

Yes, I know that now too. Not sure what to do with this issue though.

**Comment by adamchainz** [comment]
Ah right. I just found this repo from a friend on GitHub.

You could mention it in the README at least?
